[linker] Add BCL size regression testing
We're now tracking the size of the BCL after it was processed by the linker
across various profiles we care about (currently net_4_x, monotouch and monodroid).

The way it works is that we keep a file with size measurements in the repo
and during CI we run the linker against the current state and compare.

Right now we're simply running the linker tests as they are a good approximation
of various usages (this PR additionally adds more comprehensive linker tests we had in XI).

If changes are found there's a report to check where the increase/decrease came from.
The changes can be applied via `@monojenkins commit sizediff` similar to
existing csproj and apidiff usages.

Fixes https://github.com/mono/mono/issues/6992

diff --git a/mcs/tools/linker/Makefile b/mcs/tools/linker/Makefile
--- a/mcs/tools/linker/Makefile
+++ b/mcs/tools/linker/Makefile
@@ -7,6 +7,8 @@ PROGRAM = monolinker.exe
 LIB_REFS = System System.Core System.Xml Mono.Cecil
 
 TEST_CASES := \
+	link-all/link-all.cs \
+	link-sdk/link-sdk.cs \
 	mscorlib/test-array.cs \
 	mscorlib/test-remoting.cs \
 	mscorlib/test-string-01.cs \
@@ -32,6 +34,12 @@ mscorlib/test-%.cs:
 System/test-%.cs:
 	$(TESTS_COMPILER)  -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.dll Tests/$@ /out:Tests/$(@:.cs=.exe)
 
+link-all/link-all.cs: $(wildcard Tests/link-all/*.cs)
+	$(TESTS_COMPILER) -resource:Tests/LinkerDescriptor/link-all.xml -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/I18N.MidEast.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/I18N.Other.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.Core.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.Xml.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.Runtime.Serialization.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.ComponentModel.Composition.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.Data.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.Net.Http.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/nunitlite.dll $^ /out:Tests/$(@:.cs=.exe)
+
+link-sdk/link-sdk.cs: $(wildcard Tests/link-sdk/*.cs)
+	$(TESTS_COMPILER) -resource:Tests/LinkerDescriptor/link-sdk.xml -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.Core.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.Xml.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.Xml.Linq.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.Runtime.Serialization.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.Runtime.Serialization.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.ComponentModel.Composition.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.Data.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.Net.Http.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.Data.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.Data.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.ServiceModel.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.ServiceModel.Web.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.Data.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.Json.dll  -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/System.Data.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/Mono.Data.Sqlite.dll -r:$(topdir)/class/lib/$(PROFILE_DIRECTORY)/nunitlite.dll $^ /out:Tests/$(@:.cs=.exe)
+
 run-tests: $(TEST_CASES:.cs=.exe)
 
 LINKER_OUTPUT := illink-output-$(PROFILE_DIRECTORY)
@@ -41,12 +49,48 @@ TEST_EXEC = MONO_PATH=$(LINKER_OUTPUT) $(RUNTIME) $(RUNTIME_FLAGS) --debug -O=-a
 
 .NOTPARALLEL:
 
-System/test-%.exe mscorlib/test-%.exe:
+System/test-%.exe mscorlib/test-%.exe link-all/link-%.exe link-sdk/link-%.exe:
 	@rm -rf $(LINKER_OUTPUT)
 	@mkdir $(LINKER_OUTPUT)
 	@echo Testing $@
 	$(LINKER) -a Tests/$@
 	$(TEST_EXEC) $(LINKER_OUTPUT)/$(@F)
 	@rm -rf $(LINKER_OUTPUT)
+
+BCL_ASSEMBLIES_CORE=mscorlib.dll System.dll System.Core.dll System.Xml.dll
+BCL_ASSEMBLIES=$(BCL_ASSEMBLIES_CORE) $(sort $(filter-out $(BCL_ASSEMBLIES_CORE), $(notdir $(wildcard $(PROFILE_PATH)/System.*.dll)) ))
+
+COMMA=,
+REPORT_FILE=$(PROFILE)-linked-size.csv
+
+bcl-size-current: compile-tests
+	@echo "App,$$(echo '$(BCL_ASSEMBLIES)' | tr ' ' ',')" > $(REPORT_FILE)
+	@for app in $(sort $(TEST_CASES:.cs=.exe)); do \
+		rm -rf $(LINKER_OUTPUT); \
+		mkdir $(LINKER_OUTPUT); \
+		echo Checking linked BCL size for $$app; \
+		$(LINKER) -a Tests/$$app; \
+		sizes=""; \
+		for asm in $(BCL_ASSEMBLIES); do \
+			if [ -f "$(LINKER_OUTPUT)/$$asm" ]; then size=$$(wc -c < "$(LINKER_OUTPUT)/$$asm" | tr -d "[:space:]"); else size="0"; fi; \
+			sizes+=",$$size"; \
+		done; \
+		echo "$$app$$sizes" >> $(REPORT_FILE); \
+		rm -rf $(LINKER_OUTPUT); \
+	done;
+
+bcl-size-diff:
+	@echo "Regenerating BCL Linked Size diff..."
+	$(Q) $(MAKE) bcl-size-current PROFILE=net_4_x   || true
+	$(Q) $(MAKE) bcl-size-current PROFILE=monotouch || true
+	$(Q) $(MAKE) bcl-size-current PROFILE=monodroid || true
+	@echo "Checking size differences..."
+	@mkdir -p sizediff
+	$(Q) git diff HEAD "*.csv" > temp.patch
+	$(Q) git show HEAD:./net_4_x-linked-size.csv > net_4_x-linked-size.old.csv
+	$(Q) git show HEAD:./monotouch-linked-size.csv > monotouch-linked-size.old.csv
+	$(Q) git show HEAD:./monodroid-linked-size.csv > monodroid-linked-size.old.csv
+	$(Q) sed -e "/@diffdata@/r temp.patch" -e "/@diffdata@/d" -e "/@olddata-net_4_x@/r net_4_x-linked-size.old.csv" -e "/@olddata-net_4_x@/d" -e "/@olddata-monotouch@/r monotouch-linked-size.old.csv" -e "/@olddata-monotouch@/d" -e "/@olddata-monodroid@/r monodroid-linked-size.old.csv" -e "/@olddata-monodroid@/d" -e "/@newdata-net_4_x@/r net_4_x-linked-size.csv" -e "/@newdata-net_4_x@/d" -e "/@newdata-monotouch@/r monotouch-linked-size.csv" -e "/@newdata-monotouch@/d" -e "/@newdata-monodroid@/r monodroid-linked-size.csv" -e "/@newdata-monodroid@/d" linked-size-diff.html.in > sizediff/index.html
+	$(Q) if [ -s temp.patch ]; then echo "Error: Found BCL Linked Size differences, see mcs/tools/linker/sizediff/index.html."; rm -f temp.patch *.old.csv; exit 1; else echo "No differences found."; rm -f temp.patch *.old.csv; fi
 
 include ../../build/executable.make
