Add CoreFX.issues_windows.rsp

diff --git a/scripts/ci/pipeline-netcore-runtime.yml b/scripts/ci/pipeline-netcore-runtime.yml
--- a/scripts/ci/pipeline-netcore-runtime.yml
+++ b/scripts/ci/pipeline-netcore-runtime.yml
@@ -95,12 +95,13 @@ jobs:
   - bash: |
       make -C netcore update-tests-corefx
     displayName: 'Download CoreFX Tests'
-    condition: ne(variables['poolname'], 'Hosted VS2017')
   
   - bash: |
+      errors=0
       for testdir in netcore/corefx/tests/extracted/*; do
-        scripts/ci/./run-step.sh --label=$(basename $testdir) --timeout=10m make -C netcore run-tests-corefx-$(basename $testdir)
+        scripts/ci/./run-step.sh --label=$(basename $testdir) --timeout=10m make -C netcore run-tests-corefx-$(basename $testdir) || errors=$((errors+1))
       done
+      echo $errors > .failures
     displayName: 'Run CoreFX Tests'
     timeoutInMinutes: 90
     condition: ne(variables['poolname'], 'Hosted VS2017')
@@ -110,6 +111,16 @@ jobs:
       testRunTitle: $(poolname)
       testResultsFormat: 'XUnit'
       testResultsFiles: 'netcore/corefx/tests/TestResult-*.xml'
+    condition: ne(variables['poolname'], 'Hosted VS2017')
+
+  - bash: |
+      errors=$(<.failures)
+      if [ "$errors" -ne "0" ]; then
+        echo "$errors test suits have failures";
+        exit 125
+      fi
+    displayName: 'Validate test results'
+    timeoutInMinutes: 90
     condition: ne(variables['poolname'], 'Hosted VS2017')
 
   - ${{ if and(ne(variables['System.TeamProject'], 'public'), ne(variables['Build.Reason'], 'PullRequest')) }}:
