* scripts/mono-find-provides.in: * scripts/mono-find-requires.in: error out if monodis isn't functioning properly.  Otherwise when building rpms, the provides/requires isn't generated correctly if monodis isn't present.
Fixes: bnc #227362


svn path=/trunk/mono/; revision=70445

diff --git a/scripts/mono-find-requires.in b/scripts/mono-find-requires.in
--- a/scripts/mono-find-requires.in
+++ b/scripts/mono-find-requires.in
@@ -22,8 +22,11 @@ exec_prefix=$d/..
 libdir=$prefix/@reloc_libdir@
 bindir=$d
 
-[ -x $bindir/monodis ] || exit 0;
-[ -f $libdir/libmono.so ] || exit 0;
+# Bail out if monodis or libmono is missing
+if [ ! -x $bindir/monodis ] || [ ! -f $libdir/libmono.so ] ; then
+	echo "monodis missing or unusable, exiting..."
+	exit 1
+fi
 
 
 # set LD_LIBRARY_PATH to ensure that libmono.so is found
